### PR TITLE
Fix zookeeper issues in tests

### PR DESCRIPTION
**Pull request by colinmarc**
This switches the tests to use the same zk library to create a server as it does to connect to it, so that we can remove samuel/go-zookeeper. It also gives the zk server some time to start up, since that seems to be a problem in travis.

It also fixes the caching of hadoop and zookeeper tarballs in travis, so tests should be faster there.

Yay green builds!

### CODE REVIEW

**Comment by forklady42** [comment]
Consolidating zk libraries sgtm. That being said, the travis build failed yet again. /o\

**Comment by colinmarc** [comment]
Noooo it was passing earlier. I ran it like 10 times. argh.

**Comment by colinmarc** [comment]
I know there are still issues to track down, but I just rebuilt like 100 times and can't reproduce them. Merging this as a marginal improvement (and I added some extra logging, so we can track down the issue next time).

**Comment by forklady42** [comment]
cool cool

**Pull request merged**
