### PR TITLE
Allow faster startup, by deleting ZK nodes in parallel

### PR DESCRIPTION
**Pull request by vasi-stripe**
Sometimes it takes minutes for this to run.

### CODE REVIEW

**Comment by jerry-stripe** [comment]
I'm so down for speeding up boot time, though https://github.com/stripe/sequins/pull/132/files#diff-085ac95e7286e4e0b4f7f05d0381ac81R416 makes it seem like `cleanupTree` isn't thread safe since it takes out a lock.

**Comment by vasi-stripe** [comment]
I'm pretty sure that it's thread-safe, though. If you look at what `Delete()` actually does, it just calls `request()`, which enqueues something.

I'm not sure what we're locking to protect against—maybe so we don't delete something at the same time we try to watch it, or something?

**Comment by jerry-stripe** [comment]
In that case, lgtm!

**Pull request merged**
