### PR TITLE
Small UI fixes.

### PR DESCRIPTION
**Pull request by jbalogh-stripe**
* give dbs a fixed width so each section is consistent and scannable
* drop bold from version names so that every word on the page is not bold

r? @jerry-stripe

### CODE REVIEW

**Comment by jerry-stripe** [comment]
lgtm!

**Comment by bartle-stripe** [comment]
I think this caused the partition table to wrap, making it unreadable :( I suspect what we want is to just use ~100% of the screen width?

**Comment by jerry-stripe** [comment]
@bartle-stripe Which cluster are you seeing this on? This change hasn't been rolled out anywhere yet. I will try playing around with 100% screen width to see if it doesn't make things too hard to read.

**Comment by bartle-stripe** [comment]
I just noticed it while debugging a single node (that had a custom build deployed to it).

**Comment by jerry-stripe** [comment]
Oh yeah I see it now, will increase the width considerably to compensate

**Pull request merged**
